// libs/ng/lib14/src/lib/lib14-component20/lib14-component20.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib14-component20',
  templateUrl: './lib14-component20.component.html',
  styleUrls: ['./lib14-component20.component.css'],
})
export class Lib14Component20Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}

// libs/react/lib14/src/lib/lib14-component20.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib14-component20.css';

export const Lib14Component20 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib14Component20;
