// libs/react/lib14/src/lib/lib14-component14.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib14-component14.css';

export const Lib14Component14 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib14Component14;

// libs/ng/lib14/src/lib/lib14-component14/lib14-component14.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib14-component14',
  templateUrl: './lib14-component14.component.html',
  styleUrls: ['./lib14-component14.component.css'],
})
export class Lib14Component14Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}
