// libs/ng/lib12/src/lib/lib12-component20/lib12-component20.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib12-component20',
  templateUrl: './lib12-component20.component.html',
  styleUrls: ['./lib12-component20.component.css']
})
export class Lib12Component20Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}

// libs/react/lib12/src/lib/lib12-component20.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib12-component20.css';

export const Lib12Component20 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib12Component20;
