// libs/react/lib11/src/lib/lib11-component26.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib11-component26.css';

export const Lib11Component26 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib11Component26;

// libs/ng/lib11/src/lib/lib11-component26/lib11-component26.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib11-component26',
  templateUrl: './lib11-component26.component.html',
  styleUrls: ['./lib11-component26.component.css'],
})
export class Lib11Component26Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}
