// libs/react/lib10/src/lib/lib10-component20.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib10-component20.css';

export const Lib10Component20 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib10Component20;

// libs/ng/lib10/src/lib/lib10-component20/lib10-component20.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib10-component20',
  templateUrl: './lib10-component20.component.html',
  styleUrls: ['./lib10-component20.component.css'],
})
export class Lib10Component20Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}
