// libs/ng/lib10/src/lib/lib10-component24/lib10-component24.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib10-component24',
  templateUrl: './lib10-component24.component.html',
  styleUrls: ['./lib10-component24.component.css']
})
export class Lib10Component24Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}

// libs/react/lib10/src/lib/lib10-component24.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib10-component24.css';

export const Lib10Component24 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib10Component24;
