// libs/ng/lib10/src/lib/lib10-component26/lib10-component26.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib10-component26',
  templateUrl: './lib10-component26.component.html',
  styleUrls: ['./lib10-component26.component.css'],
})
export class Lib10Component26Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}

// libs/react/lib10/src/lib/lib10-component26.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib10-component26.css';

export const Lib10Component26 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib10Component26;
