// libs/react/lib12/src/lib/lib12-component29.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib12-component29.css';

export const Lib12Component29 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib12Component29;

// libs/ng/lib12/src/lib/lib12-component29/lib12-component29.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib12-component29',
  templateUrl: './lib12-component29.component.html',
  styleUrls: ['./lib12-component29.component.css']
})
export class Lib12Component29Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}
