// libs/react/lib13/src/lib/lib13-component22.tsx
import React from 'react';
import { SHARED_CONST } from '@happyorg/shared-utils';

import './lib13-component22.css';

export const Lib13Component22 = () => {
  return (
    <div>
      <h1>Welcome to lib0-component0 component! {SHARED_CONST}</h1>
    </div>
  );
};

export default Lib13Component22;

// libs/ng/lib13/src/lib/lib13-component22/lib13-component22.component.ts
import { Component, OnInit } from '@angular/core';
import { SHARED_CONST } from '@happyorg/shared-utils';

@Component({
  selector: 'happyorg-lib13-component22',
  templateUrl: './lib13-component22.component.html',
  styleUrls: ['./lib13-component22.component.css'],
})
export class Lib13Component22Component implements OnInit {
  sharedConst = SHARED_CONST;

  constructor() {}

  ngOnInit() {}
}
